FROM python:3.11.2

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir /ChatApp

WORKDIR /ChatApp

COPY . /ChatApp/

RUN pip install --upgrade pip && pip install pip-tools && pip install -r requirements.txt 