# Generated by Django 3.1 on 2023-04-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_control', '0002_message_messageattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericfileupload',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
